//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OOO_ParfumerEntities : DbContext
    {
        public OOO_ParfumerEntities()
            : base("name=OOO_ParfumerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Order_> Order_ { get; set; }
        public virtual DbSet<Order_In_Points> Order_In_Points { get; set; }
        public virtual DbSet<PointOfIssue> PointOfIssue { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Product_In_Order> Product_In_Order { get; set; }
        public virtual DbSet<User_> User_ { get; set; }
        public virtual DbSet<User_Orders> User_Orders { get; set; }
    }
}
